### PR TITLE
Create 3.9.3

### PR DESCRIPTION
**Pull request by greg-rychlewski**

### CODE REVIEW

**Comment by josevalim** [comment]
@greg-rychlewski I wonder if it makes sense to backport several of those to v3.9 and do a new release there? Especially because I think the one with cast_params should go on the v3.9 branch. WDYT?

**Comment by greg-rychlewski** [comment]
I think that makes sense. For this repo probably everything except for the empty value stuff can go into 3.9?

I'll also modify the ecto_sql PR to be 3.9

**Comment by josevalim** [comment]
Yeah, I think everything mentioned in this PR is safe for v3.9 :)

**Comment by greg-rychlewski** [comment]
Sorry not sure if I did this right. I cherry-picked all the commits to be back-ported and changed the target branch to v3.9

**Comment by greg-rychlewski** [comment]
crap sorry, I thought I was pushing to here but I pushed directly to v3.9. I can revert them or you'd prefer to leave as is and close this PR?

**Comment by josevalim** [comment]
Perfect. :heart:

**Pull request closed without merging**
