### PR TITLE
change the Mix tasks advice to be close Getting Started.md

### PR DESCRIPTION
**Pull request by TORIFUKUKaiou**
Hi!

The Ecto is great!
Thanks a lot.

I have a proposal to improve the description.

https://github.com/elixir-ecto/ecto/blob/a017d4a0ced979fa8c610b9dcba0f760cc47f253/lib/mix/tasks/ecto.gen.repo.ex#L78

```
Don't forget to add your new repo to your supervision tree
(typically in lib/#{app}/application.ex):

    {#{inspect repo}, []}
```

I was wondering if you could improve the description in Getting Started.md ? 
Of course I see the current description is right.
So I don't mind if the pull request was rejected.

### CODE REVIEW

**Comment by josevalim** [comment]
Thank you for the PR! I think instead we should change the Mix tasks advice to simply say `#{inspect repo},` instead. WDYT?

**Comment by TORIFUKUKaiou** [comment]
Thanks for the lighting fast response!

I see now.
I want to work for this, can I? :)

**Comment by josevalim** [comment]
Yes, please!

**Comment by TORIFUKUKaiou** [comment]
I force push.

## 1. lib/mix/tasks/ecto.gen.repo.ex

lib/mix/tasks/ecto.gen.repo.ex advice is close Getting Started.md.

(a) or (b)?
I select (b).
I think that (b) is clear where he/she for Ecto beginer adds Repo.

What do you think? 

(a)
pr-3826-a

(b)
pr-3826-b

---

##  2. lib/ecto.ex

change the Ecto moduledoc to simply write MyApp.Repo, in lib/ecto.ex .

---

##  3. mix test
There are 4 failures, when I did 'mix test' on c48695b8.
https://github.com/elixir-ecto/ecto/tree/883cf145f2812c8b50dc03cca2de894f2848c87a has same error, too.
I use elixir: 1.13.1-otp-24, erlang: 24.2 .
So it keeps.

- test/ecto/query/builder/dynamic_test.exs:51
- test/ecto/query/builder/join_test.exs:24
- test/ecto/query/inspect_test.exs:271
- test/ecto/query/planner_test.exs:330

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by TORIFUKUKaiou** [comment]
Thank you very much.

**Pull request merged**
