### PR TITLE
Clearer error message when an embedded struct is expected.

### PR DESCRIPTION
**Pull request by azizk**
I tripped over this issue a while ago and only found the solution in the Elixir forum. Just want to make sure others aren't puzzled by the error message. :)

I have two questions though:
* In the first test the returned row contains a plain map and not the embedded struct. Is this correct?
* It doesn't make sense to implicitly cast a map value to the embedded struct, or would it?

### CODE REVIEW

**Comment by josevalim** [comment]
It looks correct but embeds_many expects a list of maps or a list of structs, so you need to check the cardinality for the error message.

**Comment by azizk** [comment]
The cardinality is already being checked in `Ecto.Embedded.dump/3`, isn't it? Btw, I'd suggest to rename `dump/5` and `load/4` to `dump_field/5` and `load_field/4` respectively. They confusingly look very much like the behaviour functions from `Ecto.ParameterizedType`.

Also when you pass a single embed instead of a list, like so `TestRepo.insert_all(MySchemaWithEmbed, [%{embeds: %MyEmbed{x: "x"}}])`, you get a pretty long error message:

`** (Ecto.ChangeError) value `%Ecto.RepoTest.MyEmbed{id: nil, x: "x"}` for `Ecto.RepoTest.MySchemaWithEmbed.embeds` in `insert_all` does not match type {:parameterized, Ecto.Embedded, %Ecto.Embedded{cardinality: :many, field: :embeds, on_cast: nil, on_replace: :raise, ordered: true, owner: Ecto.RepoTest.MySchemaWithEmbed, related: Ecto.RepoTest.MyEmbed, unique: true}}`

This is coming from `Ecto.Repo.Schema.dump_field!/6`. Maybe it's worth improving this as well.

**Comment by josevalim** [comment]
Yes, that is a separate discussion though. For this PR, what is important is for the error message needs to consider the cardinality. :)

**Comment by azizk** [comment]
Alright, so I added another test schema which uses an `embeds_one`. The error message is dependent on the cardinality now. But it doesn't really sound good if you ask me. For example:

`cannot dump embed ``embeds``, expected a list of Ecto.RepoTest.MyEmbed struct values but got: %{x: "x"}`

The "but got: ..." part still lists a single value so it doesn't really fit the previous statement of expecting a list of struct values...

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
