### PR TITLE
add complex subtypes support

### PR DESCRIPTION
**Pull request by vintikzzz**
[Cassandra DB](http://cassandra.apache.org/) supports different complex types such as [tuples](http://docs.datastax.com/en/cql/3.1/cql/cql_reference/tupleType.html), tuple of tuples, [maps of
maps](http://docs.datastax.com/en/cql/3.1/cql/cql_reference/tupleType.html), etc… And it is really important to modify a little bit type
validation. So migrations could looks like:
```elixir
create table(@table, primary_key: false) do
  add :id, :uuid, primary_key: true
  add :value1, {:tuple, {:integer, :string, :float}}
  add :value2, {:tuple, {:integer, :string, {:tuple, {:integer, :integer}}}}
end
```

### CODE REVIEW

**Comment by josevalim** [comment]
@vintikzzz if the `{:tuple, {:integer, :string, :float}}` is meant to denote a tuple of integer, strings or floats, I would prefer for the second element to be a list because it may have N elements. So both `{:tuple, :integer}` and `{:tuple, [:integer, :string]}` would be supported perhaps?

**Comment by vintikzzz** [comment]
@josevalim tuples by it's nature shouldn't have more then several elements, but technically you are right that it may have N elements. I have another example with maps:
```elixir
create table(@table, primary_key: false) do
  add :id, :uuid, primary_key: true
  add :value1, {:map, {:integer, :integer}}
end
```
In this case number of elements couldn't be more than two.
So I think maybe be it will be a good idea to pass both variants (tuple and list) through validation?

**Comment by josevalim** [comment]
@vintikzzz sounds like an option, yes. Try to figure out what you want to accept on your side of things and then change Ecto accordingly. :)

**Comment by josevalim** [comment]
To be clear, let's make Ecto only as extensible as it needs to be but not more. So if you need to support tuples with two elements only and lists, then that should be all.

**Comment by vintikzzz** [comment]
@josevalim Thank you for clarification. I will be there with new pull request shortly.

**Pull request closed without merging**
