### PR TITLE
Implement dynamically selected named binding

### PR DESCRIPTION
**Pull request by LostKobrakai**
Regarding #2832

### CODE REVIEW

**Comment by AndrewDryga** [comment]
Thank you, this simplifies few places for us 🎊.

**Comment by LostKobrakai** [comment]
Yeah, the part when you accidentally work on an old master and only rebase at the end. Seems like this is already in ecto.

**Comment by AndrewDryga** [comment]
@LostKobrakai I don't think that it's supported for all the cases. I believe it's still not supported for joins and/or preloads.

**Comment by LostKobrakai** [comment]
At least https://github.com/elixir-ecto/ecto/pull/3005/files#diff-c04711315c01e29757522ea2764fd871R755 is pretty much what I added.

**Pull request closed without merging**
