### PR TITLE
Avoid catch-all clause in Ecto.Registry

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by fishcakez** [comment]
Should we remove this clause and crash instead as we don't expect other messages?

**Comment by josevalim** [comment]
We will remove `super` from Elixir v1.8 so I would keep it as is.

@fishcakez It depends if you interpret stray info messages as a bug or not. I personally don't, so I am fine with keeping it as is. :)

**Comment by fishcakez** [comment]
We should then instead of being silent

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
