### PR TITLE
Add compilation warning for cycle in through assocs (#3025)

### PR DESCRIPTION
**Pull request by mkaravaev**

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @mkaravaev, this is looking promising! Is there anything we can do to help with the tests?

**Comment by mkaravaev** [comment]
Hi @josevalim, I can add a test for this. Didn't noticed that I'd added commented test code, my fault.

**Comment by josevalim** [comment]
No problem, please let us know if you have any questions.

**Comment by josevalim** [comment]
Ping @mkaravaev! :)

**Comment by mkaravaev** [comment]
@josevalim Pong! :) Sorry for delay. Working on test now.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
