### PR TITLE
Propagate parent process logger level to preloader

### PR DESCRIPTION
**Pull request by v0idpwn**
Closes https://github.com/elixir-ecto/ecto_sql/issues/602

### CODE REVIEW

**Comment by v0idpwn** [comment]
Problem: `Logger.get_process_level` and `Logger.put_process_level` function were added on Elixir 1.15.

**Comment by josevalim** [comment]
What if we fix the metadata initially and we address the level once we require Elixir v1.15?

**Comment by v0idpwn** [comment]
I like the idea of propagating logger metadata too, certainly can add that!
With regards to the level, I assume we want to support Elixir <1.15 for at least one year more (1.15.0 is not even one year old yet), and delaying this fix until then doesn't seem to be worth it. The two variants of pmap seem relatively low cost to me. WDYT?

**Comment by greg-rychlewski** [comment]
is everything inside of `Logger.get/put_process_level` also dependent on Elixir 1.15 or is there anything we can inline?

**Comment by v0idpwn** [comment]
It's very Elixir-version dependent, I'd say. 

Before 1.15 there was `enable/1`, `disable/1` and `enabled?/1` for process. We could use that, but it's a more limited feature (and is now deprecated in favor of the new APIs).

**Comment by v0idpwn** [comment]
That's fair enough, @josevalim. I'll close this one.

**Pull request closed without merging**
