### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
List of changes:

- Fix typos and grammars
- Use common source url

### CODE REVIEW

**Comment by josevalim** [comment]
I would prefer to not include the CHANGELOG for now as it is reset between major versions. Can you please remove these changes? Thanks!

**Comment by kianmeng** [comment]
> I would prefer to not include the CHANGELOG for now as it is reset between major versions. Can you please remove these changes? Thanks!

Done. :+1:

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by wojtekmach** [comment]
@kianmeng instead of adding CHANGELOG to links, we could add it to docs extras. We do this in e.g. Elixir itself and that allows us to have versioned links:

- https://hexdocs.pm/elixir/1.11/changelog.html
- https://hexdocs.pm/elixir/master/changelog.html

If you'd like to work on this, a PR would be appreciated :D

**Comment by kianmeng** [comment]
> If you'd like to work on this, a PR would be appreciated :D

@wojtekmach

Here you go, https://github.com/elixir-ecto/ecto/pull/3519 :smiley:

**Pull request merged**
