### PR TITLE
Fix getting started tutorial markup

### PR DESCRIPTION
**Pull request by deadtrickster**
Close Code block

### CODE REVIEW

**Comment by fishcakez** [comment]
Thank you :heart:

**Comment by deadtrickster** [comment]
hey could you please update hexdocs?

**Comment by ericmj** [comment]
It will usually be updated when a new release is made.

**Comment by michalmuskala** [comment]
This made the guide all messed up. I think it's worth releasing just the docs to fix this.

**Comment by ericmj** [comment]
Go ahead and do it but make sure to only include this change in the docs. We don't want the docs to include changes from master.

**Comment by michalmuskala** [comment]
@ericmj I believe that's the only commit done to master that was not released in the docs, so we should be fine.
I don't have hex bits to release new docs for ecto.

**Comment by josevalim** [comment]
Done.

**Pull request merged**
