### PR TITLE
Fix broken build

### PR DESCRIPTION
**Pull request by v0idpwn**

### CODE REVIEW

**Comment by v0idpwn** [comment]
I'm still a bit skeptical about the last PR. Please do not merge this one yet, maybe I'll change it a bit :)

**Comment by josevalim** [comment]
I will merge it only to fix the build, sorry. :) Regarding the last PR, i think we can also simply make the value be `Ecto.Type.t | term` but it is fine as is too.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by randycoulman** [comment]
Ah, whoops, that was my fault. Sorry! My editor had re-formatted the code and put the trailing `}` on the last line and I missed that when I put in the suggested change.  🤦

**Pull request merged**
