### PR TITLE
Support views in migrations #1805

### PR DESCRIPTION
**Pull request by alesasnouski**
Can we somehow rewrite update_view_sql function? We need to convert our query to raw SQL and I'm not sure that my solution is the best one.

### CODE REVIEW

**Comment by mbuhot** [comment]
Is it possible to define the views in separate files from the migrations themselves?
This becomes necessary when views need to be dropped and re-created because an underlying table column is altered.

**Comment by josevalim** [comment]
`execute File.read!("priv/migrations/view/foo.sql")`

**Comment by wojtekmach** [comment]
bonus points for `foo_v1.sql`, `foo_v2.sql` etc to trivially distinguish which files goes to `up` and `down` as well as tracking how view changes over time.

**Comment by mbuhot** [comment]
@josevalim Yeah that's pretty much how I manage views now. Is there an equivalent with views defined in `.exs` scripts using the `Migration` module and Ecto query syntax?

```elixir
defmodule MyMigration do
  use Ecto.Migration
  def change do
    Code.requre_file("priv/migrations/views/foo_v1.exs")
    create Foo.V1.view()
  end
end
```

with the view module defined like:

```elixir
defmodule Foo.V1 do
  use Ecto.Migration
  def view do
    Ecto.Migration.view(query: from(p in "posts", select: p.name), prefix: "baz")
  end
end
```

**Comment by josevalim** [comment]
@mbuhot that will work too. You could define multiple views on the same file, so you don't need multiple requires. Versioning can be done with function names.

**Comment by josevalim** [comment]
Thanks @alesasnouski. I have tried this patch on a side-project and I started to run into issues that show the approach of using queries is unfortunately flawed because Ecto may take some liberties when building queries, especially if subqueries are involved. To make matters worse if we start generating `AS` in `select` to internal purposes, that will affect views too.

I am considering going with a variant that is based on files, as we mentioned above. It is also worth noting that the new `execute/2` simplify those scenarios a bit. To create:

    execute File.read!("priv/repo/views/foo_v1.sql"), "DROP VIEW foo"

To update:

    execute File.read!("priv/repo/views/foo_v2.sql"), File.read!("priv/repo/views/foo_v1.sql")

It is a bit verbose but I am more inclined to build helpers on this direction than on top of Ecto.Query. Apologies for the false positive and thank you for your contributions!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request closed without merging**
