### PR TITLE
modifies Ecto.Repo.Supervisor to support new style child spec

### PR DESCRIPTION
**Pull request by evadne**
As per discussion in #2820, amends `Ecto.Repo.Supervisor` so once it has a wrapped child spec, it tries to use `Supervisor.init/2` instead of `Supervisor.Spec.supervise/2`.

The decision is currently implemented as an inlined function with the underlying call determined at compile time. I can change this so it happens at runtime if that is better.

### CODE REVIEW

**Comment by josevalim** [comment]
Let’s go with runtime because we don’t have to worry about performance here
and it will be cleaner. Thanks :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
We probably need a test too. :) Maybe we can set up a simple adapter that
returns a Task as child spec? Thoughts?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by evadne** [comment]
Thanks, I will make the changes. Of the 2 test environments on Travis, the older one is wonky and crashing when booting Elixir, not too sure why :(

**Comment by josevalim** [comment]
Looks great! I have removed some of the added white space and reverted some of the style changes. Just a test and we are ready to ship it. :)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
