### PR TITLE
Clearer error message when a map is expected for an embedded struct.

### PR DESCRIPTION
**Pull request by azizk**
This one is similar to the last PR I made. Last one was about `dump_field`, but I missed doing the same for `load_field`. I added an integration test but I have no idea if it's going to pass. Let's see. :)

I threw in an auto-format commit but you can ignore it if it's not important.

### CODE REVIEW

**Comment by azizk** [comment]
Looks like it's raising a different error:
```
Expected exception ArgumentError but got Ecto.Query.CastError (/src/ecto/lib/ecto/repo/queryable.ex:171: value `123` in `update` cannot be cast to type {:parameterized, Ecto.Embedded, %Ecto.Embedded{cardinality: :one, field: :item, on_cast: nil, on_replace: :raise, ordered: true, owner: Ecto.Integration.Order, related: Ecto.Integration.Item, unique: true}} in query
```

**Comment by josevalim** [comment]
To test the load callback you will need to manually insert bad data in the database, perhaps by using an insert_all with a string table name.

**Comment by azizk** [comment]
Ah right, thanks! I tried it but I'm still getting an exception from `Ecto.Repo.Queryable.load!/5` first. I'll continue checking...

**Comment by azizk** [comment]
I'm stuck and didn't have much time to check further. Gonna close this for now.

**Pull request closed without merging**
