### PR TITLE
Permissive Multi naming

### PR DESCRIPTION
**Pull request by alexauritt**
resolves: #1505 
also see earlier discussion on closed PR: #1506

### CODE REVIEW

**Comment by alexauritt** [comment]
@michalmuskala: We want to allow ANY term for a name, yes? Also I could use some guidance on where best to update the documentation.

**Comment by michalmuskala** [comment]
Yes, I think we shouldn't impose any requirements at that point.

**Comment by alexauritt** [comment]
@michalmuskala -- alright then -- gonna strip it down and keep it simple. Let me know if we're missing anything.

**Comment by michalmuskala** [comment]
Thank you! ❤️

**Pull request merged**
