### PR TITLE
Automatically define schema typespecs

### PR DESCRIPTION
**Pull request by gVolop**
i'm not the owner of this code.. 
but y not merge it?
i think that's can be really helpfully!!

### CODE REVIEW

**Comment by josevalim** [comment]
@wojtekmach is a frequent contributor to Ecto, so we will leave it up to him to contribute it or send a pull request when he feels it is ready. Thanks!

**Comment by wojtekmach** [comment]
@gVolop thanks :) I haven't opened the PR because there are 2 unresolved things still:

- how to generate types for custom modules. On the branch we assume the custom type defined `CustomType.t()`, which may be incorrect assumption and we don't have a good way to enforce it. Some other options are adding callbacks to `Ecto.Type` which doesn't seem ideal either
- whether we should allow to overwrite the generated schema's `t()` type

@josevalim I'm happy to open the PR if it moves this forward. (I'm not sure if it does, I still don't know how to handle custom types!)

**Comment by gVolop** [comment]
@wojtekmach 
in cases the custom struct have no defined type - y can't you generate the type like you did for the ecto schema?
you can take the default values of the struct `%CustomType{}` - and mapping them into type.. or - put `any()` for all fields
no?!

**Comment by wojtekmach** [comment]
> you can take the default values of the struct %CustomType{} - and mapping them into type.. or - put any() for all fields
no?!

@gVolop a custom type doesn't have to be a struct, it can be just a string, for example.

**Comment by gVolop** [comment]
i see there is `type` callback in the `Ecto.Type` behaviour, 
so, conceptually, we can say that if we can raise an error in case of not implemented callback (instead of warning) - you can use this callback to build the type ?

**Comment by wojtekmach** [comment]
that callback has different purpose, it specifies the underlying DB type. For example, if you define custom `money` type in Postgres, type would return `:money`

**Comment by gVolop** [comment]
humm... i thought that the underlying type have to be one of the existing ecto types...

@wojtekmach
sorry for bothering you.. but i think that feature can really be very useful!
 
what dyou think about add option for the `Ecto.Schema.field`, something like:
`field :name, :string, struct_type: String.t`
and while generating the type - use the `struct_type` OR map the ecto type and if custom - use the `t()` if defined or - `any()`

**Comment by wojtekmach** [comment]
We shouldnt define the typespec when the type is used on a schema, rather when the type is defined (either build in or custom type) if that makes sense. Also for typespecs we need quote expressions.

I have opened a PR and the discussion has been moved there: https://github.com/elixir-ecto/ecto/pull/2594

**Pull request closed without merging**
