### PR TITLE
Remove warnings on 1.8-dev

### PR DESCRIPTION
**Pull request by wojtekmach**

### CODE REVIEW

**Comment by wojtekmach** [comment]
There's one other warning on master that would require bumping Elixir version requirement:

```
warning: Inspect.Algebra.surround_many/5 is deprecated. Use Inspect.Algebra.container_doc/6 instead
Found at 3 locations:
  lib/ecto/changeset.ex:2552
  lib/ecto/query/inspect.ex:16
  lib/ecto/query/inspect.ex:30
```

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
We can survive with the surround_many one for a bit. :)

**Comment by wojtekmach** [comment]
Yup that's what I've figured!

**Pull request merged**
