### PR TITLE
Fixes interval examples for `from_now` and `ago`

### PR DESCRIPTION
**Pull request by victorsolis**

### CODE REVIEW

**Comment by michalmuskala** [comment]
Why is this change required? It seems `months` is a valid interval specifier, at least for postgres.

**Comment by josevalim** [comment]
@victorsolis the current examples seem to be fine. Can you plaese clarify the changes? :)

**Comment by victorsolis** [comment]
Hi Michal, 

I tested it in postgres and got this:
`** (Ecto.Query.CompileError) invalid interval: `"months"` (expected one of year, month, week, day, hour, minute, second, millisecond, microsecond)`

Maybe we should update [this](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/builder.ex#L481) instead, if `months` is indeed valid?

Apologies, I should've included this in the PR.

**Comment by josevalim** [comment]
sorry, we were the ones who got confused and thought months was fine, thank you! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
