### PR TITLE
Supporting parent_as in type/2 calls.

### PR DESCRIPTION
**Pull request by wilkinson4**
See the following [conversation](https://groups.google.com/g/elixir-ecto/c/VYV5D-1gHBk).

### CODE REVIEW

**Comment by josevalim** [comment]
I am not sure this will work. :) You are not accessing parent_as directly, rather a field of parent_as. You can try writing a test and it may not pass.

**Comment by josevalim** [comment]
Ping :)

**Comment by wilkinson4** [comment]
Updated. Hope this looks good 🤞.

**Comment by josevalim** [comment]
Hi!

Unfortunately I don't think this will work either. You are discarding the `parent_as` reference and the query will likely point to the wrong column. Do you have an application you can try your changes on to double check? :)

**Comment by josevalim** [comment]
Closing this for now. Feel free to request to reopen once the issues have been addressed. Thank you!

**Pull request closed without merging**
