### PR TITLE
Add @type t to Ecto.UUID

### PR DESCRIPTION
**Pull request by teamon**
As discussed in https://groups.google.com/forum/#!topic/elixir-ecto/C9ZOY7M-OeE

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by michalmuskala** [comment]
I wonder if it would be better to have `t :: <<_::286>>` - slightly more specific that `binary`

**Comment by teamon** [comment]
I didn't know you could do this, nice!
I guess it should be `t :: <<_ :: 288>>` (36 * 8 = 288)

**Comment by michalmuskala** [comment]
I used this and added type specs to all public functions in `Ecto.UUID` module in https://github.com/elixir-ecto/ecto/commit/2ad988a94100426f821414c5495bc967c8d4a50b

**Comment by teamon** [comment]
Awesome 🎉

**Pull request merged**
