### PR TITLE
Document ordering by an alias

### PR DESCRIPTION
**Pull request by nathanl**

### CODE REVIEW

**Comment by josevalim** [comment]
Wait, did we add this feature?! :D

**Comment by josevalim** [comment]
Ok, so I double checked and this feature does not work. It works for subqueries exclusively but it means we shouldn't document it. Of course we could make it more general purpose and have this case work but we would need to address that first. :)

**Comment by nathanl** [comment]
I'm confused. 😄 I have a working demo at https://github.com/nathanl/people_query_demo

The relevant code is:

```elixir
today = Date.utc_today()

base_query =
  from(person in Person,
    select: %{
      name: person.name,
      lifespan:
        fragment(
          # If person is alive, calculate lifespan until today
          "COALESCE(?, ?) - ? AS lifespan",
          person.death,
          ^today,
          person.birth
        )
    }
  )

base_query
|> order_by([{:asc, fragment("lifespan")}])
|> People.Repo.all()
|> IO.inspect(label: "ascending by lifespan ")

base_query
|> order_by([{:desc, fragment("lifespan")}])
|> People.Repo.all()
|> IO.inspect(label: "descending by lifespan ")
```

which logs:

```
[debug] QUERY OK source="people" db=1.0ms decode=0.6ms queue=31.4ms idle=0.0ms
SELECT p0."name", COALESCE(p0."death", $1) - p0."birth" AS lifespan FROM "people" AS p0 ORDER BY lifespan [~D[2022-02-02]]
ascending by lifespan : [
  %{lifespan: 763, name: "C"},
  %{lifespan: 25780, name: "B"},
  %{lifespan: 27545, name: "A"}
]
descending by lifespan : [
  %{lifespan: 27545, name: "A"},
  %{lifespan: 25780, name: "B"},
  %{lifespan: 763, name: "C"}
]
[debug] QUERY OK source="people" db=0.9ms queue=1.2ms idle=18.7ms
SELECT p0."name", COALESCE(p0."death", $1) - p0."birth" AS lifespan FROM "people" AS p0 ORDER BY lifespan DESC [~D[2022-02-02]]
```

Were you saying that ⬆️ is not supported, or am I misunderstanding?

**Comment by josevalim** [comment]
Oh, I am so sorry. I thought the name was coming from the map key! But it is coming from the fragment. Doh!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
