### PR TITLE
Fix `prepare_opts` test

### PR DESCRIPTION
**Pull request by greg-rychlewski**
This was causing the CI to fail. If you have any time, was also wondering if you could let me know why it's emitting a `CaseClauseError`. Thanks!

### CODE REVIEW

**Comment by greg-rychlewski** [comment]
Does this turn function heads into cases?

`@compile {:inline, get_dynamic_repo: 0, prepare_opts: 2}`

**Comment by josevalim** [comment]
> Does this turn function heads into cases?

Yes!

**Review by josevalim — APPROVED** [review]

**Comment by josevalim** [comment]
Actually, we should remove the inline. The CaseClauseError won't be as readable in error messages.

**Comment by greg-rychlewski** [comment]
@josevalim How is this? Sorry there are some end of line whitespace removals.

**Review by josevalim — APPROVED** [review]

**Pull request merged**
