### PR TITLE
Don't allow interpolated nil in literal keyword list when building query

### PR DESCRIPTION
**Pull request by fsanggang**
#3021

### CODE REVIEW

**Comment by fsanggang** [comment]
I believe this fixes the specific issue in #3021, namely interpolated nils in keyword lists. But as the tests show, there is a side-effect of causing another kind of nil comparison to raise a compilation error instead of an argument error, and I'm not sure that's acceptable? 🤔

**Comment by michalmuskala** [comment]
I don't think this is all the way in a place where we'd want the check to happen, since it would only apply to actual `nil` literals - the test we'd want to check it with, should be something along the lines of:

```elixir
var = nil
from p in Post, where: [id: ^var]
```

That's probably need to expand into some sort of a runtime check for `nil` like we do in other places.

**Comment by josevalim** [comment]
The proper solution is to change this clause:

https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/query/builder/filter.ex#L26

to something like this:

```elixir
{field, in_value}, params when is_atom(field) ->
  {out_value, {params, :acc}} = Builder.escape(in_value, {binding, field}, {params, :acc}, vars, env)
  value = maybe_check_for_nils(in_value, out_value, field)
  {{:{}, [], [:==, [], [to_escaped_field(binding, field), value]]}, params}
```

where:

```
defp maybe_check_for_nils({:^, _, [_]}, out_value, field) do
  quote do
    Ecto.Query.Builder.Filter.not_nil!(unquote(out_value), field)
  end
end

defp maybe_check_for_nils(_, out_value, _field) do
  out_value
end
```

And the `not_nil` should check if the value is `nil` or not and raise a meaningful error message.

**Comment by fsanggang** [comment]
Thank you for the tips and pointers!

**Comment by josevalim** [comment]
Merged locally, thank you! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request closed without merging**
