### PR TITLE
Raise error when non-existing field is being validated

### PR DESCRIPTION
**Pull request by wojtekmach**
Solves part of #1107.

### CODE REVIEW

**Comment by josevalim** [comment]
Sounds good to me. @michalmuskala?

**Comment by michalmuskala** [comment]
Are we sure this should be an argument error? 

Other than that a :+1: from me.

**Comment by josevalim** [comment]
ArgumentError sounds good. Let's give this patch a try. @wojtekmach should we add a bit more information? "unknown field #{inspect field} for changeset on #{inspect changeset.data}"?

**Comment by wojtekmach** [comment]
Adding more information sounds good, I'll get on it this evening. I was initially thinking about listing all available fields in the error message, but inspecting the data sounds good too.

**Comment by wojtekmach** [comment]
@josevalim updated, this is how it looks like now:

preview

**Pull request merged**
