### PR TITLE
Fix whitespace issues from Credo report

### PR DESCRIPTION
**Pull request by martinsvalin**
You [mentioned on twitter](https://twitter.com/elixirlang/status/795699495547863041) that you'd appreciate help closing Credo complaints.

I took a few minutes fixing the low-hanging whitespace issues. I'm purposely not touching any of the issues that require more refactoring (complexity or nesting warnings), to make code review straight-forward. These should all be style issues.

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by martinsvalin** [comment]
Since you recently started using Ebert, I'll comment that the link to the PR review gives a 404 (and once a 503), both in the auto-comment, and in the checks integration details link. Could be because I'm reading stale data, as I'm checking the link minutes after the PR was created.

Still, maybe something to look into, to give a better experience with Ebert.

**Comment by josevalim** [comment]
@martinsvalin thank you, the bug has already been reported. :)  Your link for now is: https://ebertapp.io/github/elixir-ecto/ecto/reviews/9

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
