### PR TITLE
Allow nil as first argument to Repo.preload

### PR DESCRIPTION
**Pull request by jfrolich**

### CODE REVIEW

**Comment by shhavel** [comment]
@jfrolich  I think also a corresponding test should be added. Thanks

**Comment by jfrolich** [comment]
Thanks for the feedback! I am not very comfortable around the source code yet, so let me know if the location of the test is right!

**Comment by shhavel** [comment]
@jfrolich I think the location of the test is perfect.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
