### PR TITLE
Chapter for Test Environment Setup

### PR DESCRIPTION
**Pull request by philippneugebauer**
https://github.com/elixir-ecto/ecto/issues/2465

### CODE REVIEW

**Comment by philippneugebauer** [comment]
@josevalim I've added the chapter

**Comment by philippneugebauer** [comment]
Should the `aliases` function for the `test` command also be included? I am not sure about that.

**Comment by josevalim** [comment]
Thanks @philippneugebauer! I have done some changes that expand a bit more the point of using the sandbox. Can you please review my changes?

I think we should also mention the aliases in mix.exs because it makes running tests more convenient, could you please add that too?

Thanks!

**Comment by philippneugebauer** [comment]
I have also added the `aliases`. Should be good to merge now

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
