### PR TITLE
Support order_by in associations

### PR DESCRIPTION
**Pull request by coop**
See https://github.com/elixir-ecto/ecto/pull/2853#issuecomment-445472020 for previous implementation / discussion.

I wanted to submit so you know I haven't forgotten about it. I've tested it in the app that I'm working on, still needs tests in Ecto though.

TODO:

- [ ] tests
- [ ] docs

### CODE REVIEW

**Comment by josevalim** [comment]
@coop looks excellent so far! :heart:

**Comment by josevalim** [comment]
Ping!

**Comment by josevalim** [comment]
Hi @coop! I will go ahead and close this for now but if you  would like to work on this feature, just let us  know!

**Comment by coop** [comment]
Hi @josevalim - sorry for not responding earlier. I'll get tests sorted and reopen when ready. Thanks for your help so far.

**Pull request closed without merging**
