### PR TITLE
Create Navigating Relations.md

### PR DESCRIPTION
**Pull request by mfrasca**
This is a guide I'm missing.  maybe it's somewhere else and I didn't see it, but I grepped the `guides` directory for the names of the macros, and found nothing relevant.

### CODE REVIEW

**Comment by josevalim** [comment]
Yes, we don't have an introductory guide on associations. One is definitely welcome. If it helps, you can see the previous association guide as an example: https://github.com/elixir-ecto/ecto/blob/8bbed3b3840cd15d67d4117dbde24a17476af172/guides/Associations.md

The guide was removed though because people had many complaints about its structure and clarity. So please don't rely heavily on it.

Also, please note that we don't have much time to invest in Ecto, so opposite to the guides in elixir-lang, I personally won't be of much help here, sorry.

**Comment by mfrasca** [comment]
> we don't have much time to invest in Ecto

humph ­— as you know, I know close to nothing of Elixir, so I will need some help or at least hints.  the above one, I'll check.  I want to give a relevant and complex example in this guide, and I intend to explain (to myself as well as to others) how to navigate links once we have defined them in schemas.  the ultimate goal for myself is to be able to complete [what I started here](https://elixirforum.com/t/parsing-custom-query-language-and-query-ecto-database/23243).

-- I've registered for the Medellín conference (just the conference), you aren't going to be there, or are you?

**Comment by josevalim** [comment]
Great!

Unfortunately I won't be at the event. I hope you will have a great time though!

**Comment by mfrasca** [comment]
@josevalim , is there a core team for ecto ? as I've written in a TODO here, I'm also interested in automating the migration process, if I can be of any help.

**Comment by josevalim** [comment]
There is a core team, we all follow the issues tracker. :)

What do you mean by  automating migrations?  If you mean Django style migrations, we have debated about this in the past and it isn't a good fit for Ecto because we may design schemas that are a subset of the database table. Such automation would belong to a separate package.

**Comment by mfrasca** [comment]
about migrations, I guess I can review the text where I mention them.
to me, it would make sense to have a somewhat more verbose boilerplate migration file,
like mentioning the fields I added.
but I guess it's fine this way, one has to pay attention to what one does, after all.

I'm curious about comments, reviews, while I'm writing this.
it makes sense to me, and I'm learning while writing.

**Comment by mfrasca** [comment]
next thing, I'll probably check your old `associations` guide against what I've written here.  I miss the use of most options when creating the associations.  I have been focusing on navigation, not on data insertion.  anyway, it might be next week Monday or Tuesday.  I'd very much appreciate feedback.

**Comment by mfrasca** [comment]
I am realizing, a bit late, that there's also no guide for migrations (or I don't see it.  I grepped the guides for 'gen\.migration' and found nothing relevant: one initial migrations and my own examples).  and I have some major difficulties understanding how to perform data migrations, let alone explain it to others.

**Comment by josevalim** [comment]
The Getting Started guide does show to create a migration and migrate it that should be enough for further guides. The Ecto.Migration module should also be quite complete.

**Comment by mfrasca** [comment]
I don't find the text in `h Ecto.Migration` of much help.  the point where I am stuck is: I have a column with a text that actually contains two parts, and I want the migration to split these two parts, and one part is the conceptual primary key of a new table.
concretely: `plants.name` being split in `accessions.code` and `plants.code`.
the data migration needs to create a new accession from a plant if necessary, move some data from plants to accessions, or check that the already moved data is consistent with the current, and keep the remaining data  in plants.

**Comment by mfrasca** [comment]
I found a [relevant link](https://hashrocket.com/blog/posts/ecto-migrations-simple-to-complex), containing at least one thing I would not have guessed (`flush`).

**Comment by mfrasca** [comment]
and I'm getting help from [the elixir forum](https://elixirforum.com/t/looking-for-reviewers-a-howto-guide-on-associations/23396).  but can't we start publishing this?  and add a thick warning like 
## work in progress
or something?  this would work as an invitation to review, I think.

**Comment by josevalim** [comment]
Maybe you can move it to your fork then? And have PRs there?

I don’t think we should merge work in progress generally, because if nobody
finishes it later, we will either remove it (like the previous guide) or
have to finish it ourselves.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by mfrasca** [comment]
it is in my fork.  you mean that I merge it into `master`?
I generally finish what I start.  although accidents can always happen.

**Comment by mfrasca** [comment]
it is in my `master` now.

**Comment by josevalim** [comment]
Hi @mfrasca. Sorry for the lack of feedback here. At least I let you know upfront that would be the case. :)

I took an overall look at the guide and I have some concerns:

1. The guide is currently too long
2. The guide talks about things that I don't think would belong to an association guide, such as data migration, complex search queries with substrings, etc
3. The domain of the guide is quite interesting but because it is quite specific, it may complicate the understanding of Ecto. For example, I am not a native speaker and I had a hard time grasping some of the associations

I am not sure how to move forward. At the moment, I think this guide would require changes in order to be merged but I have limited time to review it and provide the necessary feedback and at the same time I don't want to ask you to do more work when it may not be merged at the end. 

At the same time, I think this could be a nice material on data modelling with Ecto which could be published elsewhere. It is just (currently) out of scope for what we envisioned for introductory and focused association guides. Sorry.

**Comment by josevalim** [comment]
In any case, thank you a lot for your work and contributions. Here and in elixir-lang! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by mfrasca** [comment]
> this could be a nice material on data modelling with Ecto which could be published elsewhere

as said, this is a piece of documentation that I felt was missing.  I gave it the title, then I found close to nothing here on migrations (change/up/down/data), and well, that's how it went.  I could not build a step by step guide without migrations, and I had no documentation for which I could say "just refer to that".

I realize very clearly what I wrote is not an 'howto', it's a not-even-too-small tutorial.  which I'm sure you can use somewhere, you only need to decide where to put it.

I think that real life examples are much better than twisting simple stuff into becoming interesting.

as a 'howto' it's too long, but if it's a tutorial, I think not.  if it's repeating points, that's something that tutorials should do.  I could put in a personal page, and you can link to it, and later consider embedding it in whatever other document, possibly on a different domain.

next thing I will describe is user management, that will mean the one-to-one associations, where we have a base user table, then user data for authentication, user data for nurseries (viveros) (to be used in the source), user data for taxonomists (to be used in verifications).

I don't mind if you don't include it, it's anyway better for me to write stuff down than to just do it.  I always hope to motivate others join me in this AGPL software I'm writing (http://ghini.me) (https://ghini.github.io/idea/2018/04/21/what's-the-difference.html)

**Comment by mfrasca** [comment]
> I am not sure how to move forward

I also would not know.  you still have no guide on associations, and no proper guide on migrations.  nothing that really explains that change/up/down stuff.  if you care to do that, I suggest you open two different pull requests on the two subjects, and let me commit to them.  I'm fine with you defining the headers of the different sections and paragraphs.  and even stating a limit in amount of words that should be enough to cover each subject.  I suggest we do first migrations.

the initial migration;
an easy to invert migration;
one where we remove or redefine a column;
one with data that needs be migrated.

I'm still not too sure about Elixir & Co., as compared to Django, parts of it are highly interesting.  I'll place questions on the forum on how to do in Elixir&Co some of what I'm doing in Django and some that I find easy to do in Python.

**Comment by josevalim** [comment]
Often we don't have a particular material on Ecto, but we do have about using Ecto within Phoenix, and those would explain some or many of the concepts you find lacking in the official docs.

Given that you plan to move into authentication and user management, I would say it is definitely out of scope for Ecto, so I believe going to your personal page is a good choice. In Ecto I would be interested in something more meal piece which is easier to maintain.

I also think some of it should also be improved in the docs. For example, I am doing a pass on  Ecto.MIgrator and Ecto.Migration right now.

I really appreciate you being flexible here but I am still reluctant in asking for your contributions because my time in reviewing it and providing feedback is limited here. :) 

Have a great weekend!

**Comment by josevalim** [comment]
New docs for migrations are up: https://hexdocs.pm/ecto_sql/Ecto.Migration.html

**Comment by mfrasca** [comment]
> New docs for migrations are up: https://hexdocs.pm/ecto_sql/Ecto.Migration.html

where's the sources, to contribute PR?

for example: »A notable command in this regard is execute/2, which is reversible in change/0 by accepting a pair of plain SQL strings. The first is run on forward migrations (up/0) and the second when rolling back (down/0).« … not a clue what this means.

**Comment by josevalim** [comment]
Source is here: https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/migration.ex

**Comment by mfrasca** [comment]
let's say I'm going to produce a tutorial, not an howto, but I need more visibility, to increase the exposition to criticism, where there's more chance that others might participate to this document?

as it stands now, it's parked on a lot where nobody sees it, and without seeing it, there's little chance they would criticize it, and without criticism it stays as it is, and [as long as it stays as it is, you will keep it parked on this lot](https//youtu.be/EH2KHpoGBUU).

**Comment by josevalim** [comment]
I would say the best option is to publish it and collect feedback on places
like Elixir Forum, /r/elixir, etc. You can also reach out to projects like
Elixir School but I don’t know what is their workflow.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Pull request closed without merging**
