### PR TITLE
Raise when empty list is given to `values/2`

### PR DESCRIPTION
**Pull request by greg-rychlewski**
Closes https://github.com/elixir-ecto/ecto/issues/4522

### CODE REVIEW

**Review by josevalim — APPROVED** [review]

**Comment by fuelen** [comment]
I think it would be great to mention this in docs as well. It is not obvious that empty list must be handled explicitly. I caught this error in production.

**Comment by greg-rychlewski** [comment]
@fuelen Thank you that's a good callout. I will update the docs.

Out of curiosity do you know of any other standard way that this is handled?

**Comment by fuelen** [comment]
> Out of curiosity do you know of any other standard way that this is handled?

If we talk about elegant ways, then I don't know any

**Comment by josevalim** [comment]
I have asked chatgpt and it suggested generating `(SELECT NULL WHERE false)`, which I think is better than failing. WDYT?

**Comment by fuelen** [comment]
It will work, but it is no longer a VALUES statement :slightly_smiling_face: Don't know whether this is a problem.
Columns and types should be defined as well, so in a more complex scenario it will look like this
```sql
SELECT * FROM (SELECT NULL::uuid, NULL::text, NULL::int WHERE false) AS v1 ("id", "name", "age")
```

**Comment by josevalim** [comment]
I don't think it is a problem in this case, but maybe @greg-rychlewski disagrees. :)

**Comment by greg-rychlewski** [comment]
I think it could be a bit jarring to see such a different query in the logs if you're investigating unexpected input. But I also agree it is not good that it raises.

Since I can't think of anything better then I would go with it because I agree raising is the worst option.

**Comment by warmwaffles** [comment]
@josevalim is it really wise to send that along the connection and wait for the db to respond though?

**Comment by greg-rychlewski** [comment]
It could be part of a left join like this

```sql
select * from test left join (select null where false) as n  on true;
```

**Comment by greg-rychlewski** [comment]
I am still a bit unsure but after thinking about it more, it might not be so bad to let the query go through and then raise at the driver level. My reasoning:

1. It keeps the query the same as the user wrote it, so that it is not surprising to see something different in your logs.
2. It is closer to the behaviour you will get in other systems like `psql`. Where you will get an error if you try to use an empty values list.
3. It leaves the option open for databases that want to support empty values lists. I don't know of any but I know in general some databases introduce nonstandard behaviour for convenience.

Probably point 2 is the most contentious because sometimes Ecto helps and sometimes it doesn't. In this case I could see a case for saying "ok you asked for an empty list, you got it". Similar to if you ask not a non-existent table.

If we go this route then I still to clean up the SQL because we have some issues like missing types.

**Comment by josevalim** [comment]
Any route is fine by me. :+1:

**Pull request merged**
